plugins {
    id 'java'
}

group = 'de.minecraftgilde'
version = '1.0.8'

def pluginVersion = project.version.toString()
def paperApiVersion = '26.1.2.build.66-stable'
def essentialsxVersion = '2.21.2'

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        url = 'https://repo.essentialsx.net/releases/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paperApiVersion}"
    compileOnly("net.essentialsx:EssentialsX:${essentialsxVersion}") {
        exclude group: 'org.spigotmc', module: 'spigot-api'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
    options.compilerArgs += ['-Xlint:deprecation', '-Xlint:removal']
}

tasks.processResources {
    filteringCharset = 'UTF-8'
    inputs.property('version', pluginVersion)

    filesMatching('plugin.yml') {
        expand(version: pluginVersion)
    }
}
